const TimezoneList = [
    { id: 'Pacific/Midway',  text: '(GMT-11:00) Midway Island'},
    { id: 'US/Samoa', text: '(GMT-11:00) Samoa'},
    { id: 'US/Hawaii',  text: '(GMT-10:00) Hawaii'},
    { id: 'US/Alaska',  text: '(GMT-09:00) Alaska'},
    { id: 'US/Pacific',  text: '(GMT-08:00) Pacific Time (US & Canada)'},
    { id: 'America/Tijuana',  text: '(GMT-08:00) Tijuana'},
    { id: 'US/Arizona',  text: '(GMT-07:00) Arizona'},
    { id: 'US/Mountain',  text: '(GMT-07:00) Mountain Time (US & Canada)'},
    { id: 'America/Chihuahua',  text: '(GMT-07:00) Chihuahua'},
    { id: 'America/Mazatlan',  text: '(GMT-07:00) Mazatlan'},
    { id: 'America/Mexico_City',  text: '(GMT-06:00) Mexico City'},
    { id: 'America/Monterrey',  text: '(GMT-06:00) Monterrey'},
    { id: 'Canada/Saskatchewan',  text: '(GMT-06:00) Saskatchewan'},
    { id: 'US/Central',  text: '(GMT-06:00) Central Time (US & Canada)'},
    { id: 'US/Eastern',  text: '(GMT-05:00) Eastern Time (US & Canada)'},
    { id: 'US/East-Indiana',  text: '(GMT-05:00) Indiana (East)'},
    { id: 'America/Bogota',  text: '(GMT-05:00) Bogota'},
    { id: 'America/Lima',  text: '(GMT-05:00) Lima'},
    { id: 'America/Caracas',  text: '(GMT-04:00) Caracas'},
    { id: 'Canada/Atlantic',  text: '(GMT-04:00) Atlantic Time (Canada)'},
    { id: 'America/La_Paz',  text: '(GMT-04:00) La Paz'},
    { id: 'America/Santiago',  text: '(GMT-03:00) Santiago'},
    { id: 'Canada/Newfoundland',  text: '(GMT-03:30) Newfoundland'},
    { id: 'America/Buenos_Aires',  text: '(GMT-03:00) Buenos Aires'},
    { id: 'America/Godthab',  text: '(GMT-03:00) Greenland'},
    { id: 'Atlantic/Stanley',  text: '(GMT-03:00) Stanley'},
    { id: 'Atlantic/Azores',  text: '(GMT-01:00) Azores'},
    { id: 'Atlantic/Cape_Verde',  text: '(GMT-01:00) Cape Verde Is.'},
    { id: 'Africa/Casablanca',  text: '(GMT+01:00) Casablanca'},
    { id: 'Europe/Dublin',  text: '(GMT) Dublin'},
    { id: 'Europe/Lisbon',  text: '(GMT) Lisbon'},
    { id: 'Europe/London',  text: '(GMT) London'},
    { id: 'Africa/Monrovia',  text: '(GMT) Monrovia'},
    { id: 'Europe/Amsterdam',  text: '(GMT+01:00) Amsterdam'},
    { id: 'Europe/Belgrade',  text: '(GMT+01:00) Belgrade'},
    { id: 'Europe/Berlin',  text: '(GMT+01:00) Berlin'},
    { id: 'Europe/Bratislava',  text: '(GMT+01:00) Bratislava'},
    { id: 'Europe/Brussels',  text: '(GMT+01:00) Brussels'},
    { id: 'Europe/Budapest',  text: '(GMT+01:00) Budapest'},
    { id: 'Europe/Copenhagen',  text: '(GMT+01:00) Copenhagen'},
    { id: 'Europe/Ljubljana',  text: '(GMT+01:00) Ljubljana'},
    { id: 'Europe/Madrid',  text: '(GMT+01:00) Madrid'},
    { id: 'Europe/Paris',  text: '(GMT+01:00) Paris'},
    { id: 'Europe/Prague',  text: '(GMT+01:00) Prague'},
    { id: 'Europe/Rome',  text: '(GMT+01:00) Rome'},
    { id: 'Europe/Sarajevo',  text: '(GMT+01:00) Sarajevo'},
    { id: 'Europe/Skopje',  text: '(GMT+01:00) Skopje'},
    { id: 'Europe/Stockholm',  text: '(GMT+01:00) Stockholm'},
    { id: 'Europe/Vienna',  text: '(GMT+01:00) Vienna'},
    { id: 'Europe/Warsaw',  text: '(GMT+01:00) Warsaw'},
    { id: 'Europe/Zagreb',  text: '(GMT+01:00) Zagreb'},
    { id: 'Europe/Athens',  text: '(GMT+02:00) Athens'},
    { id: 'Europe/Bucharest',  text: '(GMT+02:00) Bucharest'},
    { id: 'Africa/Cairo',  text: '(GMT+02:00) Cairo'},
    { id: 'Africa/Harare',  text: '(GMT+02:00) Harare'},
    { id: 'Europe/Helsinki',  text: '(GMT+02:00) Helsinki'},
    { id: 'Europe/Istanbul',  text: '(GMT+03:00) Istanbul'},
    { id: 'Asia/Jerusalem',  text: '(GMT+02:00) Jerusalem'},
    { id: 'Europe/Kiev',  text: '(GMT+02:00) Kyiv'},
    { id: 'Europe/Minsk',  text: '(GMT+03:00) Minsk'},
    { id: 'Europe/Riga',  text: '(GMT+02:00) Riga'},
    { id: 'Europe/Sofia',  text: '(GMT+02:00) Sofia'},
    { id: 'Europe/Tallinn',  text: '(GMT+02:00) Tallinn'},
    { id: 'Europe/Vilnius',  text: '(GMT+02:00) Vilnius'},
    { id: 'Asia/Baghdad',  text: '(GMT+03:00) Baghdad'},
    { id: 'Asia/Kuwait',  text: '(GMT+03:00) Kuwait'},
    { id: 'Africa/Nairobi',  text: '(GMT+03:00) Nairobi'},
    { id: 'Asia/Riyadh',  text: '(GMT+03:00) Riyadh'},
    { id: 'Europe/Moscow',  text: '(GMT+03:00) Moscow'},
    { id: 'Asia/Tehran',  text: '(GMT+03:30) Tehran'},
    { id: 'Asia/Baku',  text: '(GMT+04:00) Baku'},
    { id: 'Europe/Volgograd',  text: '(GMT+03:00) Volgograd'},
    { id: 'Asia/Muscat',  text: '(GMT+04:00) Muscat'},
    { id: 'Asia/Dubai',  text: '(GMT+04:00) Dubai'},
    { id: 'Asia/Tbilisi',  text: '(GMT+04:00) Tbilisi'},
    { id: 'Asia/Yerevan',  text: '(GMT+04:00) Yerevan'},
    { id: 'Asia/Kabul',  text: '(GMT+04:30) Kabul'},
    { id: 'Asia/Karachi',  text: '(GMT+05:00) Karachi'},
    { id: 'Asia/Tashkent',  text: '(GMT+05:00) Tashkent'},
    { id: 'Asia/Kolkata',  text: '(GMT+05:30) Kolkata'},
    { id: 'Asia/Kathmandu',  text: '(GMT+05:45) Kathmandu'},
    { id: 'Asia/Yekaterinburg',  text: '(GMT+05:00) Ekaterinburg'},
    { id: 'Asia/Almaty',  text: '(GMT+06:00) Almaty'},
    { id: 'Asia/Dhaka',  text: '(GMT+06:00) Dhaka'},
    { id: 'Asia/Novosibirsk',  text: '(GMT+07:00) Novosibirsk'},
    { id: 'Asia/Bangkok',  text: '(GMT+07:00) Bangkok'},
    { id: 'Asia/Jakarta',  text: '(GMT+07:00) Jakarta'},
    { id: 'Asia/Krasnoyarsk',  text: '(GMT+07:00) Krasnoyarsk'},
    { id: 'Asia/Chongqing',  text: '(GMT+08:00) Chongqing'},
    { id: 'Asia/Hong_Kong',  text: '(GMT+08:00) Hong Kong'},
    { id: 'Asia/Kuala_Lumpur',  text: '(GMT+08:00) Kuala Lumpur'},
    { id: 'Australia/Perth',  text: '(GMT+08:00) Perth'},
    { id: 'Asia/Singapore',  text: '(GMT+08:00) Singapore'},
    { id: 'Asia/Taipei',  text: '(GMT+08:00) Taipei'},
    { id: 'Asia/Ulaanbaatar',  text: '(GMT+08:00) Ulaan Bataar'},
    { id: 'Asia/Urumqi',  text: '(GMT+08:00) Urumqi'},
    { id: 'Asia/Irkutsk',  text: '(GMT+08:00) Irkutsk'},
    { id: 'Asia/Seoul',  text: '(GMT+09:00) Seoul'},
    { id: 'Asia/Tokyo',  text: '(GMT+09:00) Tokyo'},
    { id: 'Australia/Adelaide',  text: '(GMT+10:30) Adelaide'},
    { id: 'Australia/Darwin',  text: '(GMT+09:30) Darwin'},
    { id: 'Asia/Yakutsk',  text: '(GMT+10:00) Yakutsk'},
    { id: 'Australia/Brisbane',  text: '(GMT+10:00) Brisbane'},
    { id: 'Australia/Canberra',  text: '(GMT+11:00) Canberra'},
    { id: 'Pacific/Guam',  text: '(GMT+10:00) Guam'},
    { id: 'Australia/Hobart',  text: '(GMT+11:00) Hobart'},
    { id: 'Australia/Melbourne',  text: '(GMT+11:00) Melbourne'},
    { id: 'Pacific/Port_Moresby',  text: '(GMT+10:00) Port Moresby'},
    { id: 'Australia/Sydney',  text: '(GMT+11:00) Sydney'},
    { id: 'Asia/Vladivostok',  text: '(GMT+10:00) Vladivostok'},
    { id: 'Asia/Magadan',  text: '(GMT+11:00) Magadan'},
    { id: 'Pacific/Auckland',  text: '(GMT+12:00) Auckland'},
    { id: 'Pacific/Fiji',  text: '(GMT+12:00) Fiji'},
];

export default TimezoneList
